name: Manual Trigger with Inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy?"
        required: true
        default: "staging"
      version:
        description: "Version to deploy"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"

