# .github/workflows/ci.yml
name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  use-reusable-ci:
    uses: ./.github/workflows/reusable-test.yml
    with:
      python_version: "3.10"

