name: Test Secret

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret exists
        run: |
          if [ -z "$MY_SECRET_KEY" ]; then
            echo "❌ Secret is missing"
            exit 1
          else
            echo "✅ Secret is present and not empty"
          fi
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}

      - name: Use secret internally
        run: |
          echo "$MY_SECRET_KEY" > /tmp/secret.txt
          echo "Secret saved to a file (not printed)"
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}

